<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.dawex.sigourney</groupId>
		<artifactId>sigourney-trustframework</artifactId>
		<version>2.3.0</version>
	</parent>

	<artifactId>sigourney-verifiable-credentials-model</artifactId>

	<name>sigourney-verifiable-credentials-model</name>
	<description>Sigourney Verifiable Credential model</description>
	<url>https://github.com/dawex/sigourney</url>

	<dependencies>
		<dependency>
			<groupId>com.dawex.sigourney</groupId>
			<artifactId>sigourney-verifiable-credentials-core</artifactId>
		</dependency>

		<!-- Tests -->
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>