package com.dawex.sigourney.trustframework.vc.model.v2210.serialization;

public class Format {
	public static final String DATA_PRODUCT_AGGREGATION_OF = "DATA_PRODUCT_AGGREGATION_OF";

	public static final String DATA_PRODUCT_CREDENTIAL_SUBJECT = "DATA_PRODUCT_CREDENTIAL_SUBJECT";

	public static final String DATA_PRODUCT_ISSUER = "DATA_PRODUCT_ISSUER";

	public static final String DATA_PRODUCT_PROVIDED_BY = "DATA_PRODUCT_PROVIDED_BY";

	public static final String DATA_PRODUCT_TERMS_AND_CONDITIONS_URI = "DATA_PRODUCT_TERMS_AND_CONDITIONS_URI";

	public static final String DATA_PRODUCT_VERIFIABLE_CREDENTIAL = "DATA_PRODUCT_VERIFIABLE_CREDENTIAL";

	public static final String DATA_RESOURCE_CREDENTIAL_SUBJECT = "DATA_RESOURCE_CREDENTIAL_SUBJECT";

	public static final String DATA_RESOURCE_COPYRIGHT_OWNED_BY = "DATA_RESOURCE_COPYRIGHT_OWNED_BY";

	public static final String DATA_RESOURCE_EXPOSED_THROUGH = "DATA_RESOURCE_EXPOSED_THROUGH";

	public static final String DATA_RESOURCE_ISSUER = "DATA_RESOURCE_ISSUER";

	public static final String DATA_RESOURCE_PRODUCED_BY = "DATA_RESOURCE_PRODUCED_BY";

	public static final String DATA_RESOURCE_VERIFIABLE_CREDENTIAL = "DATA_RESOURCE_VERIFIABLE_CREDENTIAL";

	public static final String ORGANISATION_CREDENTIAL_SUBJECT = "ORGANISATION_CREDENTIAL_SUBJECT";

	public static final String ORGANISATION_ISSUER = "ORGANISATION_ISSUER";

	public static final String ORGANISATION_VERIFIABLE_CREDENTIAL = "ORGANISATION_VERIFIABLE_CREDENTIAL";

	public static final String TERMS_AND_CONDITIONS_CREDENTIAL_SUBJECT = "TERMS_AND_CONDITIONS_CREDENTIAL_SUBJECT";

	public static final String TERMS_AND_CONDITIONS_ISSUER = "TERMS_AND_CONDITIONS_ISSUER";

	public static final String TERMS_AND_CONDITIONS_VERIFIABLE_CREDENTIAL = "TERMS_AND_CONDITIONS_VERIFIABLE_CREDENTIAL";

	private Format() {
		// no instance allowed
	}
}
