package com.dawex.sigourney.trustframework.vc.model.v2411.serialization;

public class Format {

	public static final String DATA_PRODUCER_CREDENTIAL_SUBJECT = "DATA_PRODUCER_CREDENTIAL_SUBJECT";

	public static final String DATA_PRODUCER_VERIFIABLE_CREDENTIAL = "DATA_PRODUCER_VERIFIABLE_CREDENTIAL";

	public static final String DATA_PRODUCT_AGGREGATION_OF = "DATA_PRODUCT_AGGREGATION_OF";

	public static final String DATA_PRODUCT_CREDENTIAL_SUBJECT = "DATA_PRODUCT_CREDENTIAL_SUBJECT";

	public static final String DATA_PRODUCT_PROVIDED_BY = "DATA_PRODUCT_PROVIDED_BY";

	public static final String DATA_PRODUCT_VERIFIABLE_CREDENTIAL = "DATA_PRODUCT_VERIFIABLE_CREDENTIAL";

	public static final String DATA_RESOURCE_COPYRIGHT_OWNED_BY = "DATA_RESOURCE_COPYRIGHT_OWNED_BY";

	public static final String DATA_RESOURCE_CREDENTIAL_SUBJECT = "DATA_RESOURCE_CREDENTIAL_SUBJECT";

	public static final String DATA_RESOURCE_PRODUCED_BY = "DATA_RESOURCE_PRODUCED_BY";

	public static final String DATA_RESOURCE_VERIFIABLE_CREDENTIAL = "DATA_RESOURCE_VERIFIABLE_CREDENTIAL";

	public static final String DATA_SET_EXPOSED_THROUGH = "DATA_SET_EXPOSED_THROUGH";

	public static final String DATA_SET_CREDENTIAL_SUBJECT = "DATA_SET_CREDENTIAL_SUBJECT";

	public static final String DATA_SET_VERIFIABLE_CREDENTIAL = "DATA_SET_VERIFIABLE_CREDENTIAL";

	public static final String ISSUER_CREDENTIAL_SUBJECT = "ISSUER_CREDENTIAL_SUBJECT";

	public static final String ISSUER_VERIFIABLE_CREDENTIAL = "ISSUER_VERIFIABLE_CREDENTIAL";

	public static final String LEGAL_DOCUMENT_CREDENTIAL_SUBJECT = "LEGAL_DOCUMENT_CREDENTIAL_SUBJECT";

	public static final String LEGAL_DOCUMENT_INVOLVED_PARTIES = "LEGAL_DOCUMENT_INVOLVED_PARTIES";

	public static final String LEGAL_DOCUMENT_VERIFIABLE_CREDENTIAL = "LEGAL_DOCUMENT_VERIFIABLE_CREDENTIAL";

	public static final String LEGAL_PERSON_CREDENTIAL_SUBJECT = "LEGAL_PERSON_CREDENTIAL_SUBJECT";

	public static final String LEGAL_PERSON_VERIFIABLE_CREDENTIAL = "LEGAL_PERSON_VERIFIABLE_CREDENTIAL";

	public static final String PHYSICAL_RESOURCE_CREDENTIAL_SUBJECT = "PHYSICAL_RESOURCE_CREDENTIAL_SUBJECT";

	public static final String PHYSICAL_RESOURCE_MAINTAINED_BY = "PHYSICAL_RESOURCE_MAINTAINED_BY";

	public static final String PHYSICAL_RESOURCE_VERIFIABLE_CREDENTIAL = "PHYSICAL_RESOURCE_VERIFIABLE_CREDENTIAL";

	public static final String SERVICE_OFFERING_AGGREGATION_OF_RESOURCE = "SERVICE_OFFERING_AGGREGATION_OF_RESOURCE";

	public static final String SERVICE_OFFERING_CREDENTIAL_SUBJECT = "SERVICE_OFFERING_CREDENTIAL_SUBJECT";

	public static final String SERVICE_OFFERING_LEGAL_DOCUMENT = "SERVICE_OFFERING_LEGAL_DOCUMENT";

	public static final String SERVICE_OFFERING_PROVIDED_BY = "SERVICE_OFFERING_PROVIDED_BY";

	public static final String SERVICE_OFFERING_VERIFIABLE_CREDENTIAL = "SERVICE_OFFERING_VERIFIABLE_CREDENTIAL";

	public static final String TERMS_AND_CONDITIONS_URL = "TERMS_AND_CONDITIONS_URL";

	private Format() {
		// no instance allowed
	}
}
